# Generated by Django 3.2.12 on 2022-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('combination_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('fat', models.FloatField()),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('kcal', models.IntegerField()),
                ('price', models.IntegerField()),
                ('protein', models.FloatField()),
                ('sodium', models.FloatField()),
                ('sugar', models.FloatField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'combination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CombinationPost',
            fields=[
                ('combination_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('comb_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('likes_cnt', models.IntegerField()),
                ('statistics', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'combination_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('fat', models.FloatField()),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('kcal', models.IntegerField()),
                ('length', models.IntegerField()),
                ('menu_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('protein', models.FloatField()),
                ('sodium', models.FloatField()),
                ('sugar', models.FloatField()),
                ('weight', models.IntegerField()),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_year', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('is_diet', models.TextField()),
                ('profile_img', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('subti', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
