// import axios from "axios";

export default{
  state: {
    sandList: [
      {
        id: 1,
        name: "sand1",
        basic: "에그마요",
        score: 1.5,
        desc: "닭가슴살로 만든 치키 슬라이스를 담백하게 즐겨보세요.",
        nutri: 300,
        ingre: ["플랫브래드", "오이1", "토마토1"],
        price: 5400,
      },
      {
        id: 2,
        name: "sand2",
        basic: "터키 베이컨 아보카도",
        score: 2.5,
        desc: "맛난 샌드위치2~",
        nutri: 250,
        ingre: "토마토2",
        price: 6400,
      },
      {
        id: 3,
        name: "sand3",
        score: 3.5,
        desc: "맛난 샌드위치3~",
        basic: "치킨 슬라이스",
        nutri: 350,
        ingre: "토마토3",
        price: 7400,
      },
      {
        id: 4,
        name: "sand4",
        basic: "스테이크&치즈",
        score: 4.5,
        desc: "맛난 샌드위치4~",
        nutri: 450,
        ingre: "토마토4",
        price: 8400,
      },
      {
        id: 5,
        name: "sand5",
        basic: "터키 베이컨 아보카도",
        score: 5.5,
        desc: "맛난 샌드위치5~",
        nutri: 550,
        ingre: "토마토5",
        price: 9400,
      },
      {
        id: 6,
        name: "sand1",
        basic: "에그마요",
        score: 1.5,
        desc: "닭가슴살로 만든 치키 슬라이스를 담백하게 즐겨보세요.",
        nutri: 300,
        ingre: ["플랫브래드", "오이1", "토마토1"],
        price: 5400,
      },
      {
        id: 7,
        name: "sand2",
        basic: "터키 베이컨 아보카도",
        score: 2.5,
        desc: "맛난 샌드위치2~",
        nutri: 250,
        ingre: "토마토2",
        price: 6400,
      },
      {
        id: 8,
        name: "sand3",
        score: 3.5,
        desc: "맛난 샌드위치3~",
        basic: "치킨 슬라이스",
        nutri: 350,
        ingre: "토마토3",
        price: 7400,
      },
      {
        id: 9,
        name: "sand4",
        basic: "스테이크&치즈",
        score: 4.5,
        desc: "맛난 샌드위치4~",
        nutri: 450,
        ingre: "토마토4",
        price: 7400,
      },
      {
        id: 10,
        name: "sand1",
        basic: "에그마요",
        score: 1.5,
        desc: "닭가슴살로 만든 치키 슬라이스를 담백하게 즐겨보세요.",
        nutri: 300,
        ingre: ["플랫브래드", "오이1", "토마토1"],
        price: 5400,
      },
      {
        id: 11,
        name: "sand2",
        basic: "터키 베이컨 아보카도",
        score: 2.5,
        desc: "맛난 샌드위치2~",
        nutri: 250,
        ingre: "토마토2",
        price: 6400,
      },
      {
        id: 12,
        name: "sand3",
        score: 3.5,
        desc: "맛난 샌드위치3~",
        basic: "치킨 슬라이스",
        nutri: 350,
        ingre: "토마토3",
        price: 7400,
      },
      {
        id: 13,
        name: "sand4",
        basic: "스테이크&치즈",
        score: 4.5,
        desc: "맛난 샌드위치4~",
        nutri: 450,
        ingre: "토마토4",
        price: 9400,
      },
      {
        id: 14,
        name: "sand5",
        basic: "터키 베이컨 아보카도",
        score: 5.5,
        desc: "맛난 샌드위치5~",
        nutri: 550,
        ingre: "토마토5",
        price: 8400,
      },
      {
        id: 15,
        name: "sand5",
        basic: "터키 베이컨 아보카도",
        score: 5.5,
        desc: "맛난 샌드위치5~",
        nutri: 550,
        ingre: "토마토5",
        price: 8400,
      },
      {
        id: 16,
        name: "sand5",
        basic: "터키 베이컨 아보카도",
        score: 5.5,
        desc: "맛난 샌드위치5~",
        nutri: 550,
        ingre: "토마토5",
        price: 8400,
      },
    ],
  },
  getters: {
    sandList: (state) => state.sandList,
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
}
